msaa = 9
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', 'glasses1']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]

# PBR
[materials.glasses1]
vs = "glasses1.vert"
fs = "glasses1.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.glasses1.samplers]
tex_diffuse="glasses1_glasses1_BaseColor.png"
tex_normal="glasses1_glasses1_Normal.png"
tex_metallic="glasses1_glasses1_Metallic.png"
tex_roughness="glasses1_glasses1_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
