msaa = 10
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', 'glasses2']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]

# PBR
[materials.glasses2]
vs = "glasses2.vert"
fs = "glasses2.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.glasses2.samplers]
tex_diffuse="glsses2_glasses2_BaseColor.png"
tex_normal="glsses2_glasses2_Normal.png"
tex_metallic="glsses2_glasses2_Metallic.png"
tex_roughness="glsses2_glasses2_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
